### ISSUE TITLE
Does hegel have type `any` or no `any` ?

### ISSUE THREAD

**Issue by Raynos** [JSMonk/hegel#209]
I saw that the website documentation say that the type system has no "any" in it.

Then I read the type definition of the builtin `Array` ( https://github.com/JSMonk/hegel/blob/master/packages/typings/standard/index.d.ts#L246 )

And the `some()` method on the array has `any` for the `thisArg` parameter.

This looks like a contradiction.

**Comment by JSMonk** [comment]
Hi @Raynos
Hegel doesn't have `any` type. (It has "unknown" instead which is equivalent of [`unknown` in TypeScript](https://mariusschulz.com/blog/the-unknown-type-in-typescript) and [`mixed` in Flow.js](https://flow.org/en/docs/types/mixed/).
But, you mentioned right, that inside `d.ts` files we still have `any`, because Hegel tries to fully understand `Definition Language`.
But, in duration of the analysis of a `d.ts` files `any` will be converted to `unknown` and you will not have ability to use it as `any`.

**Comment by Raynos** [comment]
Converting any to unknown is a neat trick. I like it.

I’ve gone pretty far down the type inference hole with https://github.com/Raynos/jsig

I’m excited that someone else is making a pass at a sound system. I had to give up as I couldn’t figure out how to implement generics ...

**Comment by JSMonk** [comment]
@Raynos 
I interpret generic as a function at the type.
Also, you can help us, if you are interested in building a static type checker with a sound type system. We will happy to a new contributor ^_^
